### ISSUE TITLE
Isla Duala; Lingor; Panthera

### ISSUE THREAD

**Issue by adios113** [adios113/blackwatchint#13]
http://www.armaholic.com/page.php?id=27416
http://www.armaholic.com/page.php?id=29469
http://www.armaholic.com/page.php?id=27699

**Comment by ShiFoo** [comment]
Maps accepted and upload with Modpack 09.11.

**Comment by ShiFoo** [comment]
Reopening: Lingor is not uploaded yet. I think aDi will close it again it its done
