### ISSUE TITLE
Altis Combat First Responder has incorrect quantity of QuikClot

### ISSUE THREAD

**Issue by Fourjays** [adios113/blackwatchint#14]
1st CFR slot on Altis has 20x QuikClot. Should be 5x.

**Comment by adios113** [comment]
Map doesnt matter, the loadouts are all the same on all the maps. Faction?

**Comment by Fourjays** [comment]
Default faction when spawning (USMC I believe).

**Comment by adios113** [comment]
Awaiting confirmation.
