### ISSUE TITLE
Esseker causing random CTD.

### ISSUE THREAD

**Issue by adios113** [adios113/blackwatchint#32]
Esseker is causing random CTD whenever you try to change a map from Esseker to another one both on the server and while doing this from editor. Reproduction rate: 2/10.

**Comment by adios113** [comment]
I need confirmation from someone else than me.

**Comment by ShiFoo** [comment]
I sometimes have a memory error when leaving a server playing esseker. It says something like "Could perform command 'read' on 0x00000004" or something. I from my side can confirm it. It looks like a memory pointer is invalid. Should be responsibility of the maker of esseker

**Comment by adios113** [comment]
After discussion during the meeting, we decided to delete the Esseker from the Modpack.
