### ISSUE TITLE
Laxxeman's Dynasound (Sonic cracks)

### ISSUE THREAD

**Issue by adios113** [adios113/blackwatchint#36]
**Mod Description:**  Adds sonic cracks to the game, enchanting the immersion in our gameplay. (Size: less than 1mb)

https://youtu.be/MrflxAVbp6g

**Download link:** https://dl.dropboxusercontent.com/u/57490126/Releases/%40DS_SonicCracks.rar

**Comment by wingatex** [comment]
Tested it, works fin but in my opinion dosnt really add a lot

**Comment by adios113** [comment]
Added to the metting agenda.

**Comment by adios113** [comment]
Rejected.
