### ISSUE TITLE
Burnes Armories - FV4034 Challenger 2 TES

### ISSUE THREAD

**Issue by adios113** [adios113/blackwatchint#37]
**Description:** This mod adds The British MBT Challenger 2, it adds different MBTs with different camouflage pattens. The MBTs have a full made interior that can be showen in first person. 

**Download link:**
Link for download: http://www.armaholic.com/page.php?id=27205

**Comment by wingatex** [comment]
This mod requires AGM, does not work

**Comment by adios113** [comment]
it doesn't anymore. Don't judge mods based on their description.

**Comment by adios113** [comment]
Added myself to perform a test with this mod, since Ryan's test results were unsuccesful - mod didnt work at all.

**Comment by adios113** [comment]
**Link to updated version 12:**

https://www.dropbox.com/s/46ewpdgxs4wfhzm/%40Burnes_Challenger.rar?dl=0

Works, removes AGM dependency.
Overall the tank works similair to the Bundeswehr's Leopold Tank. Custom Interior, working loader seat and comes with two variants - wooden, desert. Good quality.

**Some screenshots:** http://steamcommunity.com/id/adiospl93/screenshots

**Comment by adios113** [comment]
Added to the meeting agenda

**Comment by adios113** [comment]
Accepted to the modpack.
