### ISSUE TITLE
No Flashlights for Russian weapons.

### ISSUE THREAD

**Issue by TheGrandVizier** [adios113/blackwatchint#47]
Currently, we dont have a way to have OPFOR use flashlights unless using a specific model of an AK or western weaponry entirely.
I was under the impression jointrails should allow western attachments on eastern weapons. I guess i was wrong.

**Comment by adios113** [comment]
most of the RHS' aks dont have the rails - thats the think. We are currently considering redoing the Russian loadouts with instead of AK74, using the AK12 which is compatible with the western attachments, since it has rails.
