### ISSUE TITLE
Disable Global and Side of all tempaltes.

### ISSUE THREAD

**Issue by TheGrandVizier** [adios113/blackwatchint#50]
All templates must have Side chat and global chat disabled.
The only chats that should be available ingame are group channel and directional, if that even exists still.

**Comment by ShiFoo** [comment]
COuld you please elaborate on what you mean by that?

**Comment by TheGrandVizier** [comment]
Clarified in OP.
(Side and Global chat channels ingame)

**Comment by ShiFoo** [comment]
Ok, and why is it needed? We only use it in emergency situations, like server lagging or technical issues. And for that i find them quite useful.

**Comment by adios113** [comment]
For that we are using steam messaging.

To do:

add this line to description.ext for each template.: 

disableChannels[]={0,1};

**Comment by TheGrandVizier** [comment]
The decision was made more than a year ago now.
It was disabled for a long long time, and the scoreboard was disabled also. It's too META, and the chat ruins videos and creates extra editing requirements when it is used. Also, it hampers players immersion, which we value.

For emergency situation and technical situation, we want players to use steam messaging, as TS pokes are also disabled. Steam is the perfect solution because it is opened in overlay and unlike TS does not require a tab-out. 

This is further accommodated by an in-interview explanation to recruits that the steamgroup member list is there for them to use in order to add people to steam based on community and operational requirement.

**Comment by adios113** [comment]
Will be out with the next template update 09.11.2015

**Comment by ShiFoo** [comment]
Good explanation. Makes sense!

**Comment by ShiFoo** [comment]
Implemented with Modpack 09.11.
