### ISSUE TITLE
Inquery: Is it possible to define more groups for factions with too few?

### ISSUE THREAD

**Issue by TheGrandVizier** [adios113/blackwatchint#52]
This is a question.

Some factions that we have do not have enough Groups defined that can be spawned.
For example, ISTS only has 2 man patrols as spawnable groups. anything larger, you need to assemble yourself from individuals and then copy paste them as a group.

Is it possible to manually define (permanently) more groups from the existing individual pool?

**Comment by adios113** [comment]
If we get mod author permission to edit his mod, then yes, but still things like that are not our priority right now, cause it requires us to learn some more advanced modding stuff and until the Tech team works flawlessly and we got rid of some major issues and new features, we cant split to take care of it now. Probably in the beggining of the 2016.
