### ISSUE TITLE
UK Special Forces Mod Update 1.7

### ISSUE THREAD

**Issue by ShiFoo** [adios113/blackwatchint#60]
http://www.armaholic.com/page.php?id=19345

Changelog:
v 1.7
- Fixed: uniforms errors
- added ported A2 uniforms: arctic suites, MTP PCUs, NBC and CQB suite
- CRW CQB units are now equipped with blu suites and gas-masks
- added new MICH helmet models
- added SD ammo to all units (good for stealth missions) and P226 to SAS/SBS
- added optional config for vehicles that are now disabled by default
- adjusted OPS CORE size
- added BONUS units: NBC, PCU 
- Reworked camouflage textures
- improved: units loadout, groups and config

**Comment by adios113** [comment]
That's not the mod we have. We don't use the Massi mods at all since the latest big update.
