### ISSUE TITLE
Australia 3.00 - 4.04

### ISSUE THREAD

**Issue by adios113** [adios113/blackwatchint#7]
#Changelog

v4.04
- Trees removed from Darwin and Adelaide airports to allow large planes to auto land without crashing.
- Speedhumps removed as they were bugged with custom cars.

v4.01
**Fixed**
- Fixed: roads no longer slippery for custom cars (car packs checked, MrShounka and Jonzies cars).
- Fixed: cars stopping on one surface Texture.
- Fixed: More Building heights Adjusted.
- Fixed: Replaced Arma 2 piers with Arma 3 in several cities.
- Fixed: More road smoothing.
- Fixed: fish swimming on land.
- Fixed: Center of map added to config.
- Fixed: Deepened River leading out of desert.
- Fixed: Removed trees allowing larger planes to land in Darwin Airport.
- Fixed: Sloping land in Cairns swimming pool.
- Fixed: Floating container in Sydney.
- Fixed: Floating container in Melbourne.
- Fixed: Wheat Textures on Road Victoria.
- Fixed: Debug island made larger and moved Slightly.
- Fixed: reduced Wheat clutter.
- Plus lots more smaller bug fixes.

**New**
- New: Large GoKart Racing track In Sydney.
- New: 3 new large towns (Coober Pedy, Rockhampton, Willcania).
- New: Factory Complex North of Sydney.
- New: Mine/factory North of Coober Pedy.
- New: Fuel pumps added to all Major Airports.
- New: Large Factory North of Adelaide.
- New: factory Complex south of Melbourne.
- New: Several new small support bases.
- New: Construction Skyscraper in Sydney.
- New: Various small buildings added to countryside.
- new: Junkyard Tasmania.
- new: more detail added to Tasmania airport.
- new: runway landing lights added to Tasmania runway.
- New: Added Streetlights between Brokenhill and Bathurst.
- new: Added streetlights to Port lincoln Main Road.
- New: Added streetlights to Mt Isa.
- New: Added more content to Port Lincoln.
- New: Added Walls back to Hilltop base in Queensland.
- new: Added walls back to several areas in Pine Gap.
- new: Added roads to hilltop base.
- New: Speed humps.
- New: Texture cell size reduced from 1024 to 512.
- New: Boat refueling and dock area added to Tailem Bend
- Various rock formations and plants/trees added.

**Removed**
- Removed: Stupid Arma 1 office building that killed me while walking downstairs.
- Removed: More Arma2 objects.
- Removed: Some fences in countryside.
- Removed: Large Retextured apartment block from Sydney.
- Removed: Hotel and podesta blocks Melbourne replaced with Construction Site.

**Download Link:**
http://www.armaholic.com/page.php?id=28882

**Comment by TheGrandVizier** [comment]
Adi, I see he adds a lot of things while removing others. 
Is performance even a concern for this dev?
It is quite clear that anyone running the game on more than medium-high feels a terrible FPS drop on aussy.

**Comment by adios113** [comment]
Update probably won't go in, since the map is preventing the ammoboxes from Zeus to work as intended and probably we are going to get rid of Australia.

**Comment by adios113** [comment]
Australia has been deleted from the modpack.
